In [1]:
import torch
import numpy as np

print('PyTorch version:', torch.__version__)

np.set_printoptions(precision=3)

PyTorch version: 2.1.0


In [2]:
! python -c 'import torch; print(torch.__version__)'

2.1.0


In [3]:
a = [1, 2, 3]
b = np.array([4, 5, 6], dtype=np.int32)

t_a = torch.tensor(a)
t_b = torch.from_numpy(b)

print(t_a)
print(t_b)

tensor([1, 2, 3])
tensor([4, 5, 6], dtype=torch.int32)


In [5]:
t_a.shape

torch.Size([3])

# Tensor Manipulation

In [6]:
t_a_new = t_a.to(torch.int64)

print(t_a_new.dtype)

torch.int64


In [7]:
t = torch.rand(3, 5)

t_tr = torch.transpose(t, 0, 1)
print(t.shape, ' --> ', t_tr.shape)

torch.Size([3, 5])  -->  torch.Size([5, 3])


In [10]:
t = torch.zeros(30)

t_reshape = t.reshape(5, 6)

print(t_reshape.shape)

torch.Size([5, 6])


In [12]:
t = torch.zeros(1, 2, 1, 4, 1)

t_sqz = torch.squeeze(t, 2)

print(t.shape, ' --> ', t_sqz.shape)

torch.Size([1, 2, 1, 4, 1])  -->  torch.Size([1, 2, 4, 1])


# Mathematical Operations on Tensors

### Applying mathematical operations to tensors

In [13]:
torch.manual_seed(1)

t1 = 2 * torch.rand(5, 2) - 1
t2 = torch.normal(mean=0, std=1, size=(5, 2))

## Element wise product (keeps the same sizes of the two )

In [14]:
t3 = torch.multiply(t1, t2)
print(t3)
print(t3.shape)

tensor([[ 0.4426, -0.3114],
        [ 0.0660, -0.5970],
        [ 1.1249,  0.0150],
        [ 0.1569,  0.7107],
        [-0.0451, -0.0352]])
torch.Size([5, 2])


##  Mean of a tensor (mean(), .sum(),std())

In [15]:
t4 = torch.mean(t1, axis=0)
print(t4)

tensor([-0.1373,  0.2028])


## matrix-)matrix product  -> t_1 x T_1^T (transpose)

In [16]:
t5 = torch.matmul(t1, torch.transpose(t2, 0, 1))

print(t5)
print(t1.shape,torch.transpose(t2, 0, 1).shape,t5.shape)

tensor([[ 0.1312,  0.3860, -0.6267, -1.0096, -0.2943],
        [ 0.1647, -0.5310,  0.2434,  0.8035,  0.1980],
        [-0.3855, -0.4422,  1.1399,  1.5558,  0.4781],
        [ 0.1822, -0.5771,  0.2585,  0.8676,  0.2132],
        [ 0.0330,  0.1084, -0.1692, -0.2771, -0.0804]])
torch.Size([5, 2]) torch.Size([2, 5]) torch.Size([5, 5])


In [20]:
t6 = torch.matmul(torch.transpose(t1, 0, 1), t2)

print(t6)
print(torch.transpose(t1, 0, 1).shape, t2.shape,t6.shape)

tensor([[ 1.7453,  0.3392],
        [-1.6038, -0.2180]])
torch.Size([2, 5]) torch.Size([5, 2]) torch.Size([2, 2])


## compute L^P norm on a tensor

In [ ]:
norm_t1 = torch.linalg.norm(t1, ord=2, dim=1)

print(norm_t1)

tensor([0.6785, 0.5078, 1.1162, 0.5488, 0.1853])


In [ ]:
np.sqrt(np.sum(np.square(t1.numpy()), axis=1))

array([0.678, 0.508, 1.116, 0.549, 0.185], dtype=float32)